-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."chain_data_instructions" add column "id_without_date" boolean
--  not null default 'false';
